### ISSUE TITLE
Login Congestiómetro error

### ISSUE THREAD

**Issue by Buronn** [EL-BID/Congestiometro-GCBA#1]
Estimados,
Entiendo que la variable de entorno `ADMIN_SECRET` es la que permite ingresar en la aplicación (localhost:80). El problema radica en que el usuario `admin`, `user` o `root` no funcionan. ¿Podrían validar conmigo esta información?
Adjunto evidencia:
![image](https://github.com/EL-BID/Congestiometro-GCBA/assets/70445592/a8a5b8f4-8d88-4649-8307-8b4125a77414)
![image](https://github.com/EL-BID/Congestiometro-GCBA/assets/70445592/abf23639-d6c3-477c-b8df-2b4a50eeb4cb)
![image](https://github.com/EL-BID/Congestiometro-GCBA/assets/70445592/b56c9baf-3e6f-411d-b7b4-34c20c1f72d1)

Muchas gracias de antemano

**Comment by Argentan** [comment]
Hola @Buronn esas credenciales deberían funcionar, pero necesitaría los logs para saber dónde puede estar el error

**Comment by Vila88** [comment]
Me interesa esta pregunta ya que tengo el mismo problema.

Si lo resuelven favor de agregarme en la respuesta
Gracias

**Comment by Buronn** [comment]
Gracias por la respuesta @Argentan , adjunto los logs.
```log
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:20.460+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"streets"},"reason":"Inconsistent object: no such table/view exists in source: \"streets\"","name":"table streets in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"streets\"","code":"invalid-configuration"},"request_id":"a5119cef-c340-4f21-a2e0-b9b785e7cdc5","response_size":330,"request_mode":"error"},"request_id":"a5119cef-c340-4f21-a2e0-b9b785e7cdc5","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:20.460+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"admin_levels"},"reason":"Inconsistent object: no such table/view exists in source: \"admin_levels\"","name":"table admin_levels in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"admin_levels\"","code":"invalid-configuration"},"request_id":"51b8c914-265c-457f-8100-0991dd3468e5","response_size":350,"request_mode":"error"},"request_id":"51b8c914-265c-457f-8100-0991dd3468e5","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:20.460+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"jams"},"reason":"Inconsistent object: no such table/view exists in source: \"jams\"","name":"table jams in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"jams\"","code":"invalid-configuration"},"request_id":"902221dd-aeb5-4615-b947-8c570ebfc7a8","response_size":318,"request_mode":"error"},"request_id":"902221dd-aeb5-4615-b947-8c570ebfc7a8","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | up to date, audited 200 packages in 1s
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | 14 packages are looking for funding
congestiometro-gcba-admin-1           |   run `npm fund` for details
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | 3 moderate severity vulnerabilities
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | To address all issues, run:
congestiometro-gcba-admin-1           |   npm audit fix
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | Run `npm audit` for details.
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:21.477+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"simple_line_type"},"reason":"Inconsistent object: no such table/view exists in source: \"simple_line_type\"","name":"table simple_line_type in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"simple_line_type\"","code":"invalid-configuration"},"request_id":"22bc9a14-0ae7-4f5c-a0aa-d9213c06ecdc","response_size":366,"request_mode":"error"},"request_id":"22bc9a14-0ae7-4f5c-a0aa-d9213c06ecdc","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:21.477+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"jams_agg_line"},"reason":"Inconsistent object: no such table/view exists in source: \"jams_agg_line\"","name":"table jams_agg_line in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"jams_agg_line\"","code":"invalid-configuration"},"request_id":"d0b3c719-61cf-4f35-a19f-ddc687f18ebf","response_size":354,"request_mode":"error"},"request_id":"d0b3c719-61cf-4f35-a19f-ddc687f18ebf","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:21.477+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"predictivo_type"},"reason":"Inconsistent object: no such table/view exists in source: \"predictivo_type\"","name":"table predictivo_type in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"predictivo_type\"","code":"invalid-configuration"},"request_id":"24753746-92f8-412d-b4b9-db1bc9777567","response_size":362,"request_mode":"error"},"request_id":"24753746-92f8-412d-b4b9-db1bc9777567","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:21.477+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"histogram_type"},"reason":"Inconsistent object: no such table/view exists in source: \"histogram_type\"","name":"table histogram_type in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"histogram_type\"","code":"invalid-configuration"},"request_id":"e626f782-1f1a-446e-8793-b3d85182e9e6","response_size":358,"request_mode":"error"},"request_id":"e626f782-1f1a-446e-8793-b3d85182e9e6","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | > auth@1.0.0 start
congestiometro-gcba-admin-1           | > tsc && node ./lib/index.js
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | 
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:22.509+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"evolutivo_type"},"reason":"Inconsistent object: no such table/view exists in source: \"evolutivo_type\"","name":"table evolutivo_type in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"evolutivo_type\"","code":"invalid-configuration"},"request_id":"f362f086-a31f-4414-b785-286846a9f825","response_size":358,"request_mode":"error"},"request_id":"f362f086-a31f-4414-b785-286846a9f825","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:22.509+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"get_jams_lines"},"reason":"Inconsistent object: in function \"get_jams_lines\": no such function exists: \"get_jams_lines\"","name":"function get_jams_lines in source default","type":"function"}],"path":"$.args","error":"Inconsistent object: in function \"get_jams_lines\": no such function exists: \"get_jams_lines\"","code":"invalid-configuration"},"request_id":"cbdc955b-0f69-443a-be13-2758223a8918","response_size":404,"request_mode":"error"},"request_id":"cbdc955b-0f69-443a-be13-2758223a8918","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:22.509+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"comparativo_type"},"reason":"Inconsistent object: no such table/view exists in source: \"comparativo_type\"","name":"table comparativo_type in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"comparativo_type\"","code":"invalid-configuration"},"request_id":"aefff8fd-db50-4fbb-8823-9af86837f6a4","response_size":366,"request_mode":"error"},"request_id":"aefff8fd-db50-4fbb-8823-9af86837f6a4","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:22.509+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"get_evolutivo"},"reason":"Inconsistent object: in function \"get_evolutivo\": no such function exists: \"get_evolutivo\"","name":"function get_evolutivo in source default","type":"function"}],"path":"$.args","error":"Inconsistent object: in function \"get_evolutivo\": no such function exists: \"get_evolutivo\"","code":"invalid-configuration"},"request_id":"547d4bf8-2b40-4437-9dbc-3ddea5d43bbb","response_size":398,"request_mode":"error"},"request_id":"547d4bf8-2b40-4437-9dbc-3ddea5d43bbb","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:23.516+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"get_comparativo"},"reason":"Inconsistent object: in function \"get_comparativo\": no such function exists: \"get_comparativo\"","name":"function get_comparativo in source default","type":"function"}],"path":"$.args","error":"Inconsistent object: in function \"get_comparativo\": no such function exists: \"get_comparativo\"","code":"invalid-configuration"},"request_id":"48b6dbee-38bc-47e4-a4f2-22633396e99c","response_size":410,"request_mode":"error"},"request_id":"48b6dbee-38bc-47e4-a4f2-22633396e99c","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:23.516+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"get_summary"},"reason":"Inconsistent object: in function \"get_summary\": no such function exists: \"get_summary\"","name":"function get_summary in source default","type":"function"}],"path":"$.args","error":"Inconsistent object: in function \"get_summary\": no such function exists: \"get_summary\"","code":"invalid-configuration"},"request_id":"9f1eec49-f3aa-4a64-aa00-db70c0280923","response_size":386,"request_mode":"error"},"request_id":"9f1eec49-f3aa-4a64-aa00-db70c0280923","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:23.516+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"get_predictivo"},"reason":"Inconsistent object: in function \"get_predictivo\": no such function exists: \"get_predictivo\"","name":"function get_predictivo in source default","type":"function"}],"path":"$.args","error":"Inconsistent object: in function \"get_predictivo\": no such function exists: \"get_predictivo\"","code":"invalid-configuration"},"request_id":"c91ce7eb-b37e-40ab-b836-b4d5e243e295","response_size":404,"request_mode":"error"},"request_id":"c91ce7eb-b37e-40ab-b836-b4d5e243e295","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:23.516+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"get_lines"},"reason":"Inconsistent object: in function \"get_lines\": no such function exists: \"get_lines\"","name":"function get_lines in source default","type":"function"}],"path":"$.args","error":"Inconsistent object: in function \"get_lines\": no such function exists: \"get_lines\"","code":"invalid-configuration"},"request_id":"3de0fd8b-c2f6-4ac4-95f9-77fa4a1bd479","response_size":374,"request_mode":"error"},"request_id":"3de0fd8b-c2f6-4ac4-95f9-77fa4a1bd479","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-admin-1           | Authentication server runnig at port 8888
congestiometro-gcba-admin-1           | Hasura initialized correctely
congestiometro-gcba-postgres-1        | 2023-08-03 20:27:34.944 UTC [49] ERROR:  relation "users" does not exist at character 13
congestiometro-gcba-postgres-1        | 2023-08-03 20:27:34.944 UTC [49] STATEMENT:  INSERT INTO users(username, hash) VALUES($1, $2) ON CONFLICT (username) DO UPDATE SET hash = EXCLUDED.hash RETURNING *
congestiometro-gcba-admin-1           | /src/node_modules/pg-protocol/dist/parser.js:287
congestiometro-gcba-admin-1           |         const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
congestiometro-gcba-admin-1           |                                                                                                  ^
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | 
congestiometro-gcba-admin-1           | error: relation "users" does not exist
congestiometro-gcba-admin-1           |     at Parser.parseErrorMessage (/src/node_modules/pg-protocol/dist/parser.js:287:98)
congestiometro-gcba-admin-1           |     at Parser.handlePacket (/src/node_modules/pg-protocol/dist/parser.js:126:29)
congestiometro-gcba-admin-1           |     at Parser.parse (/src/node_modules/pg-protocol/dist/parser.js:39:38)
congestiometro-gcba-admin-1           |     at Socket.<anonymous> (/src/node_modules/pg-protocol/dist/index.js:11:42)
congestiometro-gcba-admin-1           |     at Socket.emit (node:events:513:28)
congestiometro-gcba-admin-1           |     at addChunk (node:internal/streams/readable:315:12)
congestiometro-gcba-admin-1           |     at readableAddChunk (node:internal/streams/readable:289:9)
congestiometro-gcba-admin-1           |     at Socket.Readable.push (node:internal/streams/readable:228:10)
congestiometro-gcba-admin-1           |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
congestiometro-gcba-admin-1           |   length: 104,
congestiometro-gcba-admin-1           |   severity: 'ERROR',
congestiometro-gcba-admin-1           |   code: '42P01',
congestiometro-gcba-admin-1           |   detail: undefined,
congestiometro-gcba-admin-1           |   hint: undefined,
congestiometro-gcba-admin-1           |   position: '13',
congestiometro-gcba-admin-1           |   internalPosition: undefined,
congestiometro-gcba-admin-1           |   internalQuery: undefined,
congestiometro-gcba-admin-1           |   where: undefined,
congestiometro-gcba-admin-1           |   schema: undefined,
congestiometro-gcba-admin-1           |   table: undefined,
congestiometro-gcba-admin-1           |   column: undefined,
congestiometro-gcba-admin-1           |   dataType: undefined,
congestiometro-gcba-admin-1           |   constraint: undefined,
congestiometro-gcba-admin-1           |   file: 'parse_relation.c',
congestiometro-gcba-admin-1           |   line: '1381',
congestiometro-gcba-admin-1           |   routine: 'parserOpenTable'
congestiometro-gcba-admin-1           | }
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:35.053+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"streets"},"reason":"Inconsistent object: no such table/view exists in source: \"streets\"","name":"table streets in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"streets\"","code":"invalid-configuration"},"request_id":"4e4908eb-e5f0-43e5-8f29-84754054311f","response_size":330,"request_mode":"error"},"request_id":"4e4908eb-e5f0-43e5-8f29-84754054311f","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-admin-1 exited with code 0
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:35.053+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"jam_lines"},"reason":"Inconsistent object: no such table/view exists in source: \"jam_lines\"","name":"table jam_lines in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"jam_lines\"","code":"invalid-configuration"},"request_id":"60d6d955-caf1-460f-ac27-a80f9bbc7f94","response_size":338,"request_mode":"error"},"request_id":"60d6d955-caf1-460f-ac27-a80f9bbc7f94","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:35.053+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"jams"},"reason":"Inconsistent object: no such table/view exists in source: \"jams\"","name":"table jams in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"jams\"","code":"invalid-configuration"},"request_id":"24214c94-c78a-446e-b797-4e15a7299802","response_size":318,"request_mode":"error"},"request_id":"24214c94-c78a-446e-b797-4e15a7299802","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
congestiometro-gcba-graphql-engine-1  | {"type":"http-log","timestamp":"2023-08-03T20:27:35.053+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"internal":[{"definition":{"schema":"public","name":"admin_levels"},"reason":"Inconsistent object: no such table/view exists in source: \"admin_levels\"","name":"table admin_levels in source default","type":"table"}],"path":"$.args","error":"Inconsistent object: no such table/view exists in source: \"admin_levels\"","code":"invalid-configuration"},"request_id":"485c14c2-ffc4-4876-a7b7-5344933acc22","response_size":350,"request_mode":"error"},"request_id":"485c14c2-ffc4-4876-a7b7-5344933acc22","http_info":{"status":400,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.22.0.4","method":"POST","content_encoding":null}}}
```

Por lo que veo, hay algunos problemas en los esquemas de la base de datos, por mi lado seguí las instrucciones tal cual estaban especificadas en el `INSTALL.MD`.

**Comment by Argentan** [comment]
Hola @Buronn, si todo parecería indicar que no se inicializó bien la base de datos. Hoy mandaron un PR que aborda este tema, pero no he tenido oportunidad de reproducirlo. Entretanto, te recomendarías que pares el sistema, borres la carpeta data dentro de ./database e intentes de nuevo. Cuando tenga mas información te cuento.

**Comment by Buronn** [comment]
Gracias @Argentan , te comento cuando tenga el tiempo para realizar el cambio. Muchas gracias por la respuesta.

**Comment by mehLabs** [comment]
@Vila88 @Buronn hice un PR para solucionar el problema, pero ustedes, si quieren, puede ir haciendo el fix por su cuenta. Entren al archivo /database/update.conf.sh y cambien el tipo de EOL de CRLF a LF

**Comment by Argentan** [comment]
Si @Buronn el PR que esta proponiendo @mehLabs debería solucionar este problema, si te queda algo que agregar lo poemos seguir en el otro hilo, cierro este. 
gracias
